import { MEALY, MOORE } from "../components/Minimizer";

/**
 * Checks whether two sets are equal.
 *
 * @param {Set} a - The first set to compare.
 * @param {Set} b - The second set to compare.
 * @returns {boolean} Whether the two sets are equal.
 */
function areSetsEqual(a, b) {
  return a.size === b.size && [...a].every((value) => b.has(value));
}

/**
 * Checks whether two arrays of sets are equal.
 *
 * @param {Array<Set>} a - The first array of sets to compare.
 * @param {Array<Set>} b - The second array of sets to compare.
 * @returns {boolean} Whether the two arrays of sets are equal.
 */
export function arePartitionsEqual(a, b) {
  for (let i = 0; i < a.length; i++) {
    if (!areSetsEqual(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

/**
 * Returns the partitions generated by applying the algorithm
 * to minimize the number of states in a Moore machine.
 *
 * @param {Map} states - The states of the Moore machine
 * @returns {Array} - The partitions generated by the algorithm
 */
export function getMinimizedPartitions(states, firstDistinguishablePartition) {
  let partitionsResponse = [];
  let currentPartitionArray = firstDistinguishablePartition;
  let prevPartitionArray;

  do {
    prevPartitionArray = [...currentPartitionArray];

    partitionsResponse.push(prevPartitionArray);
    currentPartitionArray = [];

    for (const [state, values] of states) {
      let assignedFlag = false;

      for (let i = 0; i < currentPartitionArray.length && !assignedFlag; i++) {
        const stateStransitionsA = states.get(state).stateStransitions;
        const [partitionRepresentative] = currentPartitionArray[i];
        const stateStransitionsB = states.get(
          partitionRepresentative
        ).stateStransitions;

        if (
          doBelongToPartition(
            stateStransitionsA,
            stateStransitionsB,
            prevPartitionArray
          )
        ) {
          currentPartitionArray[i].add(state);
          assignedFlag = true;
        }
      }

      if (!assignedFlag) {
        const newPartitionSet = new Set();
        newPartitionSet.add(state);
        currentPartitionArray.push(newPartitionSet);
      }
    }
  } while (!arePartitionsEqual(currentPartitionArray, prevPartitionArray));

  return partitionsResponse;
}

/**
 * Returns whether two states belong to the same partition.
 *
 * @param {Array} stateStransitionsA - The transitions of the first state
 * @param {Array} stateStransitionsB - The transitions of the second state
 * @param {Array} partitionsArray - ThÍe partitions to compare
 * @returns {boolean} - Whether the states belong to the same partition
 */
function doBelongToPartition(
  stateStransitionsA,
  stateStransitionsB,
  partitionsArray
) {
  for (let i = 0; i < stateStransitionsA.length; i++) {
    // A and B shared the same output since the states transitions are
    // sorted by output
    const A = stateStransitionsA[i].nextState
      ? stateStransitionsA[i].nextState
      : stateStransitionsA[i];
    const B = stateStransitionsB[i].nextState
      ? stateStransitionsB[i].nextState
      : stateStransitionsB[i];

    let belongFlag = false;
    let j = 0;
    while (j < partitionsArray.length && !belongFlag) {
      const currentPartition = partitionsArray[j];

      if (currentPartition.has(A) && currentPartition.has(B)) {
        belongFlag = true;
      }
      j++;
    }

    if (!belongFlag) {
      return false;
    }
  }

  return true;
}

/**
 * Gets the new state equivalences.
 *
 * @param {Array<Set>} lastPartition - The last partition.
 * @returns {Map} The new state equivalences.
 */
export function getNewStateEquivalences(lastPartition) {
  let newStatesMap = new Map();
  let key;

  for (let i = 0; i < lastPartition.length; i++) {
    let newStateKeysArray = [];
    for (key of lastPartition[i]) {
      newStateKeysArray.push(key);
    }
    let newStateKey = "{" + newStateKeysArray.join(",") + "}";

    newStateKeysArray.forEach((key) => {
      newStatesMap.set(key, newStateKey);
    });
  }
  return newStatesMap;
}

/**
 * Recursively finds all states that can be reached from the current state
 * @param {string} state - The current state to find reachable states from
 * @param {Set} accessedStates - A set of all states that have already been accessed
 * @param {Object} machine - The Machine being searched
 * @returns {Set} - A set of all states that can be reached from the current state
 */
export function accessState(state, accessedStates, machine) {
  accessedStates.add(state);
  const currentTransition = machine.states.get(state).stateStransitions;
  for (let i = 0; i < currentTransition.length; i++) {
    if (machine.type === MOORE) {
      if (!accessedStates.has(currentTransition[i]))
        accessState(currentTransition[i], accessedStates, machine);
    }

    if (machine.type === MEALY) {
      if (!accessedStates.has(currentTransition[i].nextState))
        accessState(currentTransition[i].nextState, accessedStates, machine);
    }
  }

  return accessedStates;
}

/**
 * Removes any states in the machine that are not reachable from the initial state
 * @param {Object} machine - The Machine to remove states from
 * @returns {string} - A string containing the inaccessible states that were removed, or "No state was removed" if no states were removed
 */
export function removeInaccessibleStates(machine) {
  const accessedStates = accessState(machine.initialState, new Set(), machine);

  if (accessedStates.size === machine.states.size) {
    return "All states are accessible";
  }

  let inaccessibleStates = "[ ";

  let counter = 0;
  for (const [key, val] of machine.states) {
    if (!accessedStates.has(key)) {
      inaccessibleStates += key;

      if (counter + 1 < machine.states.size) inaccessibleStates += ",";
      machine.states.delete(key);
    }
    counter++;
  }
  inaccessibleStates += " ]";
  return inaccessibleStates;
}
